### ISSUE TITLE
Package fails to install

### ISSUE THREAD

**Issue by LukaHorvat** [pbihler/atom-macros#10]
I'm using Atom 1.12.5 on Windows 10. This is the error

```
> runas@3.1.1 install C:\Users\darwi\AppData\Local\Temp\apm-install-dir-1161024-13564-yu5yb3\node_modules\atom-macros\node_modules\runas
> node-gyp rebuild


C:\Users\darwi\AppData\Local\Temp\apm-install-dir-1161024-13564-yu5yb3\node_modules\atom-macros\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\darwi\AppData\Local\atom\app-1.12.5\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\darwi\AppData\Local\atom\app-1.12.5\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\darwi\AppData\Local\Temp\apm-install-dir-1161024-13564-yu5yb3
`-- (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\darwi\AppData\Local\atom\app-1.12.5\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\darwi\AppData\Local\atom\app-1.12.5\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\darwi\AppData\Local\atom\app-1.12.5\resources\app\apm\node_modules\graceful-fs\polyfills.js:276:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\darwi\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\darwi\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\darwi\AppData\Local\Temp\apm-install-dir-1161024-13564-yu5yb3\node_modules\atom-macros\node_modules\runas
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\darwi\AppData\Local\Temp\apm-install-dir-1161024-13564-yu5yb3\package.json'
npm WARN apm-install-dir-1161024-13564-yu5yb3 No description
npm WARN apm-install-dir-1161024-13564-yu5yb3 No repository field.
npm WARN apm-install-dir-1161024-13564-yu5yb3 No README data
npm WARN apm-install-dir-1161024-13564-yu5yb3 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\darwi\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\darwi\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\darwi\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\darwi\\.atom\\.apmrc" "install" "C:\\Users\\darwi\\AppData\\Local\\Temp\\d-1161024-13564-prli3r\\package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\darwi\AppData\Local\Temp\apm-install-dir-1161024-13564-yu5yb3\npm-debug.log
npm ERR! code 1
```

I see it requires a python executable in path and it is. But aside from this issue, would it be possible to not require python? I'm using settings-sync with atom and would like to still be able to fully setup my whole environment with one sync, instead of requiring external dependencies.

**Comment by alflanagan** [comment]
Python is required by the node-gyp package (https://github.com/nodejs/node-gyp), which is a widely-used system for installing node packages. I expect you'll run into this issue with a lot of packages.

I believe python is part of the standard install for every system except Windows.

**Comment by LukaHorvat** [comment]
Yeah, but why does this package require it?

**Comment by alvarorodriguezestruch** [comment]
After installing Python, I got a new error:

```
> runas@3.1.1 install C:\Users\ARODRI~1\AppData\Local\Temp\apm-install-dir-11722-2984-e53h6x\node_modules\atom-macros\node_modules\runas
> node-gyp rebuild


C:\Users\ARODRI~1\AppData\Local\Temp\apm-install-dir-11722-2984-e53h6x\node_modules\atom-macros\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\arodriguez\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\arodriguez\AppData\Local\atom\app-1.14.4\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Los proyectos de esta soluci�n se van a compilar de uno en uno. Para habilitar la compilaci�n en paralelo, agregue el modificador "/m".
C:\Users\arodriguez\AppData\Local\Temp\apm-install-dir-11722-2984-e53h6x\node_modules\atom-macros\node_modules\runas\build\runas.vcxproj(20,3): error MSB4019: No se encuentra el proyecto importado "C:\Microsoft.Cpp.Default.props". Aseg�rese de que la ruta de acceso de la declaraci�n <Import> es correcta y de que el archivo se encuentra en el disco.
C:\Users\ARODRI~1\AppData\Local\Temp\apm-install-dir-11722-2984-e53h6x
`-- (empty)


gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\arodriguez\AppData\Local\atom\app-1.14.4\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\arodriguez\\AppData\\Local\\atom\\app-1.14.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\arodriguez\\AppData\\Local\\atom\\app-1.14.4\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ARODRI~1\AppData\Local\Temp\apm-install-dir-11722-2984-e53h6x\node_modules\atom-macros\node_modules\runas
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\ARODRI~1\AppData\Local\Temp\apm-install-dir-11722-2984-e53h6x\package.json'
npm WARN apm-install-dir-11722-2984-e53h6x No description
npm WARN apm-install-dir-11722-2984-e53h6x No repository field.
npm WARN apm-install-dir-11722-2984-e53h6x No README data
npm WARN apm-install-dir-11722-2984-e53h6x No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\arodriguez\\AppData\\Local\\atom\\app-1.14.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\arodriguez\\AppData\\Local\\atom\\app-1.14.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\arodriguez\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\arodriguez\\.atom\\.apmrc" "install" "C:\\Users\\ARODRI~1\\AppData\\Local\\Temp\\d-11722-2984-1gi0fdr\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ARODRI~1\AppData\Local\Temp\apm-install-dir-11722-2984-e53h6x\npm-debug.log
npm ERR! code 1
```

Thanks in advice!

**Comment by GCSBOSS** [comment]
1. Ensure python's directory is in your PATH.
2. Try creating a PYTHON var pointing to python's directory,
3. Try setting npm env var `npm -g set PYTHON = <python's dir>`
