### ISSUE TITLE
Rebuild Failed

### ISSUE THREAD

**Issue by droullois** [pbihler/atom-macros#19]
Hi,

since atom 1.50.0 I can't make atom-macros package work anymore. Here is the log I get when I try to rebuild package:

### Output:

**Rebuild Failed**

> In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:49: warning: ‘BufferReference’ is deprecated: Use MemorySpan<const uint8_t\> [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4444:3: note: in expansion of macro ‘V8_DEPRECATED’
   V8_DEPRECATED("Use CompiledWasmModule::GetWireBytesRef()",
   ^~~~~~~~~~~~~
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4386:58: note: declared here
   V8_DEPRECATED("Use MemorySpan<const uint8_t\>", struct) BufferReference {
                                                          ^~~~~~~~~~~~~~~
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:49: warning: ‘v8::WasmModuleObject::SerializedModule’ is deprecated: Use OwnedBuffer [-Wdeprecated-declarations]
   declarator __attribute__((deprecated(message)))
                                                 ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4457:3: note: in expansion of macro ‘V8_DEPRECATED’
   V8_DEPRECATED("Use CompiledWasmModule::Serialize()",
   ^~~~~~~~~~~~~
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4380:55: note: declared here
   std::pair<std::unique_ptr<const uint8_t[]\>, size_t\> SerializedModule;
                                                       ^~~~~~~~~~~~~~~~
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h: In member function ‘v8::Local<v8::Boolean\> v8::Value::ToBoolean() const’:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:10172:62: warning: ‘v8::MaybeLocal<v8::Boolean\> v8::Value::ToBoolean(v8::Local<v8::Context\>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
   return ToBoolean(Isolate::GetCurrent()-\>GetCurrentContext())
                                                              ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:2388:63: note: declared here
                     V8_WARN_UNUSED_RESULT MaybeLocal<Boolean\> ToBoolean(
                                                               ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:221,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean\>::return_t Nan::imp::ToFactory<v8::Boolean\>::convert(v8::Local<v8::Value\>)’:
../../nan/nan_converters_43_inl.h:18:51: warning: ‘v8::MaybeLocal<v8::Boolean\> v8::Value::ToBoolean(v8::Local<v8::Context\>) const’ is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
       val-\>To ## TYPE(isolate-\>GetCurrentContext())                            \
                                                   ^
../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
 X(Boolean)
 ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:2388:63: note: declared here
                     V8_WARN_UNUSED_RESULT MaybeLocal<Boolean\> ToBoolean(
                                                               ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_converters.h:67:0,
                 from ../../nan/nan.h:221,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool\>::return_t Nan::imp::ToFactory<bool\>::convert(v8::Local<v8::Value\>)’:
../../nan/nan_converters_43_inl.h:37:57: warning: ‘v8::Maybe<bool\> v8::Value::BooleanValue(v8::Local<v8::Context\>) const’ is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
   return val-\>NAME ## Value(isolate-\>GetCurrentContext());                     \
                                                         ^
../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
 X(bool, Boolean)
 ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:2433:55: note: declared here
                     V8_WARN_UNUSED_RESULT Maybe<bool\> BooleanValue(
                                                       ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:222,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function\>::return_t Nan::imp::Factory<v8::Function\>::New(Nan::FunctionCallback, v8::Local<v8::Value\>)’:
../../nan/nan_implementation_12_inl.h:105:32: warning: ‘static v8::Local<v8::Function\> v8::Function::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value\>, int)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
                           , obj));
                                ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:4027:40: note: declared here
                        Local<Function\> New(Isolate* isolate,
                                        ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:307:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value\>)’:
../../nan/nan.h:1064:78: warning: ‘v8::Local<v8::String\> v8::Value::ToString(v8::Isolate*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String\> string = from-\>ToString(v8::Isolate::GetCurrent());
                                                                              ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:2408:35: note: declared here
                     Local<String\> ToString(Isolate* isolate) const);
                                   ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value\>&)’:
../../nan/nan.h:1855:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value\>, v8::Local<v8::Value\>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)-\>Set(New(key).ToLocalChecked(), value);
                                                                ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:3260:26: note: declared here
                     bool Set(Local<Value\> key, Local<Value\> value));
                          ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String\>&, const v8::Local<v8::Value\>&)’:
../../nan/nan.h:1861:42: warning: ‘bool v8::Object::Set(v8::Local<v8::Value\>, v8::Local<v8::Value\>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)-\>Set(key, value);
                                          ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:3260:26: note: declared here
                     bool Set(Local<Value\> key, Local<Value\> value));
                          ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value\>&)’:
../../nan/nan.h:1867:44: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value\>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     New(persistentHandle)-\>Set(index, value);
                                            ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:3269:26: note: declared here
                     bool Set(uint32_t index, Local<Value\> value));
                          ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../../nan/nan.h: In member function ‘v8::Local<v8::Value\> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../../nan/nan.h:1873:61: warning: ‘v8::Local<v8::Value\> v8::Object::Get(v8::Local<v8::Value\>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         New(persistentHandle)-\>Get(New(key).ToLocalChecked()));
                                                             ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:3313:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value\> Get(Local<Value\> key));
                                                       ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../../nan/nan.h: In member function ‘v8::Local<v8::Value\> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String\>&) const’:
../../nan/nan.h:1879:55: warning: ‘v8::Local<v8::Value\> v8::Object::Get(v8::Local<v8::Value\>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(New(persistentHandle)-\>Get(key));
                                                       ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:3313:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value\> Get(Local<Value\> key));
                                                       ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.h:6:0,
                 from ../src/main.cc:1:
../../nan/nan.h: In member function ‘v8::Local<v8::Value\> Nan::AsyncWorker::GetFromPersistent(uint32_t) const’:
../../nan/nan.h:1884:57: warning: ‘v8::Local<v8::Value\> v8::Object::Get(uint32_t)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     return scope.Escape(New(persistentHandle)-\>Get(index));
                                                         ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:3317:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value\> Get(uint32_t index));
                                                       ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node_object_wrap.h:26:0,
                 from ../../nan/nan.h:54,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../nan/nan_object_wrap.h:24:37: warning: ‘bool v8::PersistentBase<T\>::IsNearDeath() const [with T = v8::Object]’ is deprecated: Garbage collection internal state should not be relied on. [-Wdeprecated-declarations]
     assert(persistent().IsNearDeath());
                                     ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:573:22: note: declared here
       V8_INLINE bool IsNearDeath() const);
                      ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan.h:2698:0,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
../../nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
../../nan/nan_object_wrap.h:67:34: warning: ‘void v8::PersistentBase<T\>::MarkIndependent() [with T = v8::Object]’ is deprecated: Objects are always considered independent. Use MarkActive to avoid collecting otherwise dead weak handles. [-Wdeprecated-declarations]
     persistent().MarkIndependent();
                                  ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8-internal.h:13:0,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:25,
                 from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:556:22: note: declared here
       V8_INLINE void MarkIndependent());
                      ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node_object_wrap.h:26:0,
                 from ../../nan/nan.h:54,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap\>&)’:
../../nan/nan_object_wrap.h:124:38: warning: ‘bool v8::PersistentBase<T\>::IsNearDeath() const [with T = v8::Object]’ is deprecated: Garbage collection internal state should not be relied on. [-Wdeprecated-declarations]
     assert(wrap-\>handle_.IsNearDeath());
                                      ^
In file included from /home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:63:0,
                 from ../../nan/nan.h:52,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/v8.h:9579:6: note: declared here
 bool PersistentBase<T\>::IsNearDeath() const {
      ^~~~~~~~~~~~~~~~~
In file included from ../src/handle_map.h:7:0,
                 from ../src/main.cc:2:
../src/unsafe_persistent.h: At global scope:
../src/unsafe_persistent.h:30:9: error: ‘v8::Handle’ has not been declared
   , v8::Handle<T\> obj) {
         ^~~~~~
../src/unsafe_persistent.h:30:15: error: expected ‘,’ or ‘...’ before ‘<’ token
   , v8::Handle<T\> obj) {
               ^
../src/unsafe_persistent.h: In function ‘void NanAssignUnsafePersistent(NanUnsafePersistent<T\>&, int)’:
../src/unsafe_persistent.h:32:64: error: ‘obj’ was not declared in this scope
     handle = NanUnsafePersistent<T\>(v8::Isolate::GetCurrent(), obj);
                                                                ^~~
In file included from ../src/main.cc:2:0:
../src/handle_map.h: At global scope:
../src/handle_map.h:11:26: error: ‘Handle’ has not been declared
   static void Initialize(Handle<Object\> target);
                          ^~~~~~
../src/handle_map.h:11:32: error: expected ‘,’ or ‘...’ before ‘<’ token
   static void Initialize(Handle<Object\> target);
                                ^
../src/main.cc:6:11: error: variable or field ‘Init’ declared void
 void Init(Handle<Object\> exports) {
           ^~~~~~
../src/main.cc:6:11: error: ‘Handle’ was not declared in this scope
../src/main.cc:6:11: note: suggested alternative: ‘HandleMap’
 void Init(Handle<Object\> exports) {
           ^~~~~~
           HandleMap
../src/main.cc:6:24: error: expected primary-expression before ‘\>’ token
 void Init(Handle<Object\> exports) {
                        ^
../src/main.cc:6:26: error: ‘exports’ was not declared in this scope
 void Init(Handle<Object\> exports) {
                          ^~~~~~~
In file included from ../../nan/nan.h:52:0,
                 from ../src/common.h:6,
                 from ../src/main.cc:1:
../src/main.cc:19:26: error: ‘Init’ was not declared in this scope
 NODE_MODULE(pathwatcher, Init)
                          ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/main.cc:19:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(pathwatcher, Init)
 ^~~~~~~~~~~
../src/main.cc:19:26: note: suggested alternative:
 NODE_MODULE(pathwatcher, Init)
                          ^
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:560:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/main.cc:19:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(pathwatcher, Init)
 ^~~~~~~~~~~
/home/<user\>/.atom/.node-gyp/.cache/node-gyp/5.0.13/include/node/node.h:221:18: note:   ‘node::Init’
 NODE_EXTERN void Init(int* argc,
                  ^~~~
make: *** [Release/obj.target/pathwatcher/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: \\>make\` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/<user\>/.atom/packages/atom-macros/node_modules/pathwatcher
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pathwatcher@6.9.0 install: \`node-gyp rebuild\`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pathwatcher@6.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/<user\>/.atom/.apm/_logs/2020-08-30T09_09_28_068Z-debug.log

**Comment by gilbertohasnofb** [comment]
Same issue on 1.51.0
