### ISSUE TITLE
Failed to load the atom-macros package

### ISSUE THREAD

**Issue by BenHollandDev** [pbihler/atom-macros#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10
**Thrown From**: [atom-macros](https://github.com/pbihler/atom-macros) package, v0.5.0

### Stack Trace

Failed to load the atom-macros package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/benholland1/.atom/packages/atom-macros/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/benholland1/.atom/packages/atom-macros/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/benholland1/.atom/packages/atom-macros/lib/macros.coffee:8:15)
  at Object.<anonymous> (/Users/benholland1/.atom/packages/atom-macros/lib/macros.coffee:3:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:619:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:52:25)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "one-light-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "atom-terminal",
      "atom-terminal-panel",
      "autocomplete-jedi",
      "language-typed-coffee-script",
      "travis-ci-status",
      "vim-mode",
      "term",
      "atom-coffee-repl"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.1.0
atom-macros, v0.5.0
autocomplete-plus, v2.7.1
bootstrap3-snippets, v0.1.1
change-case, v0.5.1
color-picker, v1.4.4
emmet, v2.3.2
file-icons, v1.5.2
linter, v0.12.0
minimap, v4.2.2
preview-plus, v1.1.19
processing-language, v0.1.0
project-manager, v1.15.5
sass-watch, v0.2.0
seti-syntax, v0.3.3

# Dev
No dev packages
```

**Comment by pbihler** [comment]
Try "apm rebuild".

> At Module version mismatch. Expected 43, got 41.

**Comment by focusaurus** [comment]
I also see this issue. Did an `apm rebuild` but it still happens when launching atom.

Atom: 0.190.0
OSX: 10.10.2
atom-macros@0.5.0

**Comment by robru** [comment]
I also got this, `apm rebuild` didn't help. Happy to cooperate if somebody wants to give me troubleshooting steps.

**Comment by pbihler** [comment]
Since the error occurs in the pathwatcher module, I updated the reference to the current 4.4.0 - hope that helps.

Does the error still occur with atom-macros 0.5.1?

**Comment by robru** [comment]
Looks good now! Thanks!
